name: Cypress Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # MANUAL TRIGGER

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Get installed Cypress version
        id: cypress-version
        run: echo "CYPRESS_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/cypress'].version)")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: cypress-cache
        with:
          path: |
            ~/.cache/cypress
          key: ${{ runner.os }}-cypress-${{ env.CYPRESS_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: decode and save
        run: |
          echo "${{ secrets.ENV }}" > .env
      - name: Run Cypress tests
        run:
          npm run cypress:all-tests

